name: Scraper_concurent

on:
  workflow_dispatch: # Manuel çalıştırma

jobs:
  scrape:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        script: [
          "scrape_api_urunlerim_rakipler_kalan1.mjs",
          "scrape_api_urunlerim_rakipler_kalan2.mjs",
          "scrape_api_urunlerim_rakipler_kalan3.mjs",
          "scrape_api_urunlerim_rakipler_kalan4.mjs",
          "scrape_api_urunlerim_rakipler_kalan5.mjs"
        ]

    steps:
      - name: Check if user is authorized
        if: github.actor != github.repository_owner
        run: |
          echo "❌ Unauthorized user: ${{ github.actor }}. Only the repository owner can run this workflow."
          exit 1

      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Install xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Install Tailscale
        run: |
          echo "Installing Tailscale"
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Start tailscaled
        run: |
          echo "Starting tailscaled"
          sudo tailscaled & sleep 5

      - name: Connect to Tailscale with Auth Key
        run: |
          echo "Connecting to Tailscale"
          sudo tailscale up --authkey=${{ secrets.TS_AUTH_KEY }} \
                            --exit-node=100.77.251.95 \
                            --accept-routes \
                            --accept-dns

      - name: Run scraper with Xvfb (Proxy-free)
        run: |
          echo "Running scraper: ${{ matrix.script }}"
          cd tests
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" node ${{ matrix.script }}

      - name: Disconnect from Tailscale
        if: always()
        run: |
          echo "Disconnecting from Tailscale"
          sudo tailscale logout
