name: Proxy

on:
  workflow_dispatch:

jobs:
  fetch-with-proxy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Connect to Tailscale
      run: |
        echo "Connecting to Tailscale"
        sudo apt-get update
        sudo apt-get install -y tailscale

        # Tailscale'i auth key ile başlatın ve çıkış düğümünü belirtin
        sudo tailscale up --authkey=${{ secrets.TS_AUTH_KEY }} --exit-node=100.77.251.95 --accept-routes --accept-dns

        echo "Tailscale bağlantısı kuruldu. Durum kontrol ediliyor..."
        tailscale status
        echo "Tailscale IP adresleri:"
        tailscale ip -4
        tailscale ip -6

    - name: Check Public IP (Should be Türkiye)
      run: |
        echo "Public IP via Türkiye Exit Node:"
        curl https://ipinfo.io
