name: Proxy

on:
  workflow_dispatch:

jobs:
  fetch-with-proxy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install and Connect to Tailscale
      run: |
        echo "Installing and Connecting to Tailscale"
        sudo apt-get update

        # Resmi Tailscale deposunu ekleyin
        curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/noble.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
        echo "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu noble main" | sudo tee /etc/apt/sources.list.d/tailscale.list

        # Paket listesini güncelle ve tailscale'i yükle
        sudo apt-get update
        sudo apt-get install -y tailscale

        # Tailscale'e bağlan
        sudo tailscale up --authkey=${{ secrets.TS_AUTH_KEY }} --exit-node=100.77.251.95 --accept-routes --accept-dns

        echo "Tailscale bağlantısı kuruldu. Durum kontrol ediliyor..."
        tailscale status
        echo "Tailscale IP adresleri:"
        tailscale ip -4
        tailscale ip -6

    - name: Check Public IP (Should be Türkiye)
      run: |
        echo "Public IP via Türkiye Exit Node:"
        curl https://ipinfo.io
