name: proxy_ok

on:
  workflow_dispatch:

jobs:
  fetch-with-proxy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Tailscale
      run: |
        echo "Installing Tailscale"
        curl -fsSL https://tailscale.com/install.sh | sh

    - name: Start tailscaled
      run: |
        echo "Starting tailscaled"
        sudo tailscaled & sleep 5

    - name: Connect to Tailscale with Auth Key
      run: |
        echo "Connecting to Tailscale with authkey"
        sudo tailscale up --authkey=${{ secrets.TS_AUTH_KEY }} \
                          --exit-node=100.77.251.95 \
                          --accept-routes \
                          --accept-dns

    - name: Check Public IP (Should be Türkiye)
      run: |
        echo "Checking IP (Should be Türkiye exit-node)"
        curl https://ipinfo.io

    - name: Disconnect from Tailscale
      if: always()
      run: |
        echo "Disconnecting from Tailscale"
        sudo tailscale logout
