name: Proxy

on:
  workflow_dispatch:

jobs:
  fetch-with-proxy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Connect to Tailscale using Auth Key
      run: |
        echo "Connecting to Tailscale using auth key"
        curl -X POST "https://api.tailscale.com/api/v2/device/authenticate" \
          -d "auth_key=${{ secrets.TS_AUTH_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.TS_AUTH_KEY }}" \
          -o device_response.json
        cat device_response.json

    - name: Check Public IP (Should be Türkiye)
      run: |
        echo "Public IP via Türkiye Exit Node:"
        curl https://ipinfo.io
