name: Proxy

on:
  workflow_dispatch:

jobs:
  fetch-with-proxy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get OAuth Token
      run: |
        echo "Getting OAuth Token"
        curl -X POST "https://api.tailscale.com/api/v2/oauth/token" \
          -d "client_id=${{ secrets.TS_OAUTH_CLIENT_ID }}" \
          -d "client_secret=${{ secrets.TS_OAUTH_SECRET }}" \
          -d "grant_type=client_credentials" \
          -d "scope=read" \
          -o token.json
        cat token.json

    - name: Connect to Tailscale via Token
      run: |
        TOKEN=$(jq -r '.access_token' token.json)
        echo "Using token: $TOKEN"
        curl -X GET "https://api.tailscale.com/api/v2/tailnet/dinamikfiyat@gmail.com/devices" \
          -H "Authorization: Bearer $TOKEN"  # Token ile kimlik doğrulama

    - name: Connect to Tailscale with Exit Node
      run: |
        echo "Connecting to Tailscale using exit node"
        curl -X POST "https://api.tailscale.com/api/v2/tailnet/dinamikfiyat@gmail.com/exitnode" \
          -H "Authorization: Bearer $TOKEN" \
          -d "exit_node=100.77.251.95"  # Türkiye'deki cihazınızın IP'sini kullanın

    - name: Check Public IP (Should be Türkiye)
      run: |
        echo "Public IP via Türkiye Exit Node:"
        curl https://ipinfo.io
