name: Run Scraping

on:
  push:
    branches:
      - main

jobs:
  scraping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install puppeteer-core

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl gnupg
          curl -sS https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run scraping script
        run: |
          cd tests
          xvfb-run --server-args="-screen 0, 1280x1024x24" node toolip_proxy.mjs
        env:
          PG_PROXYPORT: ${{ secrets.PG_PROXYPORT }}
          PG_PROXYUSERNAME: ${{ secrets.PG_PROXYUSERNAME }}
          PG_PROXYPASSWORD: ${{ secrets.PG_PROXYPASSWORD }}
