name: Scraper Workflow

on:
  workflow_dispatch: # Manuel çalıştırmaya izin ver
  # schedule:
  #   - cron: '0 3 * * *' # (Geçici olarak kapatıldı)

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check if user is authorized
        if: github.actor != github.repository_owner
        run: |
          echo "❌ Unauthorized user: ${{ github.actor }}. Only the repository owner can run this workflow."
          exit 1

      - name: Check out the code
        uses: actions/checkout@v4  # Updated to latest version

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated to latest version
        with:
          node-version: '22'
          cache: 'npm'  # Add caching for faster installs

      - name: Install xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest  # Official Chrome setup
        with:
          chrome-version: stable  # Explicitly use stable version

      - name: Install dependencies
        run: npm ci  # Clean install for CI reliability

      - name: Run scraper with Xvfb
        run: |
          cd tests
          node monitor.mjs
        env:
          PG_PROXYPORT: ${{ secrets.PG_PROXYPORT }}
          PG_PROXYUSERNAME: ${{ secrets.PG_PROXYUSERNAME }}
          PG_PROXYPASSWORD: ${{ secrets.PG_PROXYPASSWORD }}
          NODE_OPTIONS: --unhandled-rejections=strict  # Better error handling
