name: Use Türkiye Proxy via Tailscale

on:
  workflow_dispatch:

jobs:
  fetch-with-proxy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get OAuth Token
      run: |
        echo "Getting OAuth Token"
        curl -X POST "https://api.tailscale.com/api/v2/oauth/token" \
          -d "client_id=${{ secrets.TS_OAUTH_CLIENT_ID }}" \
          -d "client_secret=${{ secrets.TS_OAUTH_SECRET }}" \
          -d "grant_type=client_credentials" \
          -d "scope=read" \
          -o token.json
        cat token.json

    - name: Connect to Tailscale
      run: |
        TOKEN=$(jq -r '.access_token' token.json)
        echo "Using token: $TOKEN"
        curl -X GET "https://api.tailscale.com/api/v2/tailnet/dinamikfiyat@gmail.com/devices" \
          -H "Authorization: Bearer $TOKEN"
